# Site
repository: artfil/artfil.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Артём Филимонов
title: Java Developer
email: filimonovartemv@gmail.com
phone: +7(969)201-74-47

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username:
github_username: artfil
telegram_username: artemf9
stackoverflow_username: "14928780"
# facebook_username:
#instagram_username:
linkedin_username: артём-филимонов-5281a41ba

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Личные качества:
   - Аналитический склад ума
   - Ориентация на результат
   - Внимательность
   - Умение работать в команде
   - Инициативность
   - Целеустремлённость
   - Сильная логика

  Квалификация:
    - <mark>Base:</mark>    Java 15 Core / RESTful API / SOLID principles
    - <mark>Framework:</mark>   Spring (MVC, Security, Data, Boot) / JPA (Hibernate)
    - <mark>VCS:</mark>   Git
    - <mark>DB:</mark>    PostgreSQL / HSQLDB / H2 / MySQL
    - <mark>Test:</mark>    JUnit / Mockito
    - <mark>Bulid:</mark>   Maven
    - <mark>Deploy:</mark>    Apache Tomcat / Heroku
    - <mark>Logger:</mark>    Log4j / logback
    - <mark>Other:</mark>    JDBC / JPA / XML / Servlet / JSP / JSTL / AJAX / JWT
    - <mark>*</mark>     Знание и опыт применения концепций ООП, шаблонов проектирования, архитектурных шаблонов, UML, функционального программирования

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
