# Site
repository: artfil/artfil.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Artem Filimonov
title: Java Developer
email: filimonovartemv@gmail.com
phone: +90 (534) 259-29-65 (Turkish)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username:
github_username: artfil
telegram_username: artemf9
# stackoverflow_username: "14928780"
# facebook_username:
#instagram_username:
linkedin_username: artem-filimonov-5281a41ba

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  - Strong analytical and logical thinking
  - Results and details oriented
  - Problem-solving skills
  - Teamwork skills
  - Self starter
  - Initiative

  Qualification:
   - <mark>Base:</mark>    Java 19 Core / RESTful API / SOLID principles
   - <mark>Framework:</mark>   Spring (Boot, MVC, Security, Data, Cloud, WebFlux, Integration) / JPA (Hibernate)
   - <mark>Message broker:</mark>    RabbitMQ / Kafka
   - <mark>Orchestration:</mark>    Kubernetes
   - <mark>DB:</mark>    PostgreSQL / MySQL / MongoDB / Scylla / Clickhouse / Redis
   - <mark>Test:</mark>    JUnit / Mockito
   - <mark>Bulid:</mark>   Maven / Gradle / Docker
   - <mark>Deploy:</mark>    Apache Tomcat / Heroku
   - <mark>Logger:</mark>    Log4j / logback
   - <mark>VCS:</mark>   Git
   - <mark>Other:</mark>    Liquibase / JDBC / JPA / XML / JWT
   - <mark>*</mark>     Good knowledge of algorithms, data structures and OOP, design patterns, template architecture, UML, functional programming

# Footer
footer_show_references: false
references_title: ;

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
